### ISSUE TITLE
don't autosave if the note isn't modified

### ISSUE THREAD

**Issue by moshpirit** [stefan-niedermann/OwnCloud-Notes#104]
Sometimes I like to copy the raw marckdown code and paste in other app. OCN thinks that I edited the note and save it showing it the first if the list when I didn't.

It would be nice an option to change the sort or cancel the automatic save in these situations.

**Comment by stefan-niedermann** [comment]
I think i have a better idea about how to solve this: "Cancel editing" - Displaying a corss in the top right corner of the edit-mode.
I noticed it is a problem if you accidently deleted a line and want to undo the change, you can't. I believe this could also fix your issue.

**Comment by moshpirit** [comment]
OK, but would the app remember the last saved option? (Enabled/disabled) or would be dis/enabled by default and have an individual memory for each note?

**Comment by stefan-niedermann** [comment]
You misunderstood me. I don't want to implement an option, i want to add another button to the edit mode. So the user can choose everytime he edits an app if he wants to save the app (by pressing the back-button) or he wants to cancel the edit (by pressing the cross-button) - in the second case the editing is being undone and the edit-mode is left.

**Comment by moshpirit** [comment]
Oh, that's even better!! :D

**Comment by fxedel** [comment]
If you press the back button while editing a note – is the note saved or cancelled? Both options make sense:

- **Saved**: The made changes won't be lost.
- **Cancelled**: You made something accidentally and just want to leave this screen (without saving).

So, there's always a case where one of the options could cause data loss.

The only solution that could prevent this: Two buttons (:heavy_check_mark:/:heavy_multiplication_x:) that indicate a specific action (save/cancel) and if the user hits the back button, a dialog is opened (but only if there are changes): "Save changes? Cancel / Save"

**Comment by stefan-niedermann** [comment]
there have been two buttons at the beginning. they were removed with #26 and i think it's okay that the leaving a note means to save it. this is in 99% the action that a user wants when he leaves a note. but *sometimes* a user wants to cancel the editing without saving. only for this case there should be an :heavy_multiplication_x: top right, so the user can leave with "restoring the note from before editing"-action.
Two buttons are not a good solution - i had it, i tried it, i used it, it was hard to handle.

**Comment by korelstar** [comment]
If there is only the :heavy_multiplication_x: button and no button to save, this could be confusing. If you absolutely don't want the save button, I would propose to put the cancel action into the menu. This is also preferable since it will not be used that often.

Nevertheless, I see some problems with the implementation. Currently, all changes are directly sent to the server using the auto-save functionality (#26). Of course, the old content could be stored in a local variable and restored if desired. But then, the old content has to be sent to the server, which (again) updates the `modified` date. Hence, if you will use the cancel action, the note's modified date will be updated and the note jumps to the top of the list. That's undesired! Currently, I can't imagine a solution for this without disabling auto-save.

However, for the original scenario of the issue owner (no changes where made), another solution is required. In this case, a database update should only be made, if the content has changed. I've already put a TODO in #123 for that.
