### ISSUE TITLE
Make note directly editable

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/OwnCloud-Notes#3]
Currently it looks like when you are in a note you have to click the edit icon in the bottom right to edit it. This complicates the flow. Instead the note should be in edit mode directly, just like the web app.

**Comment by jancborchardt** [comment]
Additionally:
Editing starts at the bottom of the note. Instead I want to scroll to whichever part I’d like to edit and click there and just edit. The note which is loaded should already be in a textarea.

This also corresponds to autosave: https://github.com/stefan-niedermann/OwnCloud-Notes/issues/26 to simplify the modes which exist in the app. There should be just 2: list and note detail. But no difference between note viewing and editing.

**Comment by stefan-niedermann** [comment]
Some News: I will not implement this in the next time (takes too much time, sorry). But there is a project on Github called [MarkdownView](https://github.com/falnatsheh/MarkdownView) and [i asked the devloper](https://github.com/falnatsheh/MarkdownView/issues/13) to implement this feature. If he implements it, i can and will use it.

**Comment by jancborchardt** [comment]
But we don’t really need the Markdown view, eh? Just simple plain text totally works for now, and a simple flow is way more important at this point than having Markdown rendering.

**Comment by stefan-niedermann** [comment]
I think, MarkDown is an essential core feature of ownCloud Notes because it enables a quick overview. without markdown it looks like code for some users.
There are some users who told me, the use the web-version to create notes (primary) and the app for viewing the note (primary). I can agree this (since i use my app allday).

While there is no library i could reuse for inline-markdown, i think it is right to keep the markdown-view-mode for now.

**Comment by jancborchardt** [comment]
Well, viewing and editing should be just a single tap away – that is the tap of the cursor. Just like for the iOS notes app. No need for a different view.

The markdown rendering is a nice addition, but should ideally be inline, like in the web interface of the Notes app.

(Not sure who you asked, but the ability to quickly edit and add notes on mobile is a main reason for this app I'd say. I hardly know any mobile app which is read-only, especially not notes apps. You always have thoughts on the go.)

**Comment by HeaDBanGer84** [comment]
I really appreciate @stefan-niedermann decision. If you crate a note it has to be directly editable (like it is at the moment). But it really depence on the Use-Case. For example I have a Note with openings of small shops I visit from time to time (Post Office,Butcher ...). On locotaion I usally take a picture and add it to my note  when I sit in front of a computer next time. But I often look at this note to see if I can make to a specific shop. Of course I do this on my mobile, and it is really difficult so scroll if your touch-keyboard pops out and takes over the half screen, because the note is directly editable. But this is a problem which does not appear on the webinterface.
I vote for: diffrent devices => diffrent solutions
But keeping them as similar as possible is still a good idea

**Comment by jancborchardt** [comment]
@HeaDBanGer84 the problem you mention (with the keyboard popping up) would not happen. When you open an existing note, of course the keyboard will only appear once you tap to edit. Normal scrolling will not make the keyboard appear, effectively making the text appear as if it is read-only.

**Comment by stefan-niedermann** [comment]
May i make a proposal.
The following workflow (only a mockup) would cover both needs: a markdown-rendering and a directly editable note.

![screenshot_2016-01-29-11-12-11](https://cloud.githubusercontent.com/assets/4741199/12675849/88dfe7c4-c68d-11e5-8e62-5dbedfbb8254.png)

**Comment by jancborchardt** [comment]
That’s certainly much better, yes! :) Just reverse the views, basically. Because it emphasizes quick note taking over nice markdown viewing.

Of course again – ideal would be inline Markdown, just as it’s done in the Notes web app. But this is fine as intermediate step.

(The »Edit« header in the edit step should be the note name, just like for the markdown view though. ;)

**Comment by Bugsbane** [comment]
Is just like to say that I came here specifically to file an enhancement wish item that is exactly what Jan was requesting. I'm very familiar with markdown, but guess what, in this app I barely care about it at all. What I care about in this app is the ability to quickly edit a note and get back to what I was doing. Thus, extra clicks between the note selection screen and the note editing screen (going both ways) slow my workflow down. I'm almost never going to use markdown because it's slower than entering straight text. For my personal usecase (capturing thoughts and ideas for later) the beauty of this app is its simplicity and died, as well as it's beautiful ux in every area, bar the extra clicks between now selection and editing.

Anyway, as a user, is like to say thank you so much for a magnificent app, and please do listen to Jan. For my usecase at least, everything he had said in this issue has been 100% correct.

**Comment by jancborchardt** [comment]
> Anyway, as a user, I'd like to say thank you so much for a magnificent app, and please do listen to Jan. For my usecase at least, everything he had said in this issue has been 100% correct.

@Bugsbane btw, reading this made me cry some tears of joy. ;) Thanks a lot!

**Comment by Bugsbane** [comment]
@jancborchardt Thanks for anticipating my needs and lobbying for them before I even got here to file an issue!

**Comment by korelstar** [comment]
May be, there could be a control in the settings, whether to use the current flow or the new flow.

Personally, I would like to edit the note directly, too.

**Comment by jancborchardt** [comment]
@korelstar a core goal of Nextcloud/ownCloud is to make software as easy to use as possible. Having settings for that kind of stuff does not make any sense. ;) But good that you are also in favor of editing the note directly.
