### ISSUE TITLE
Card layout prototype

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/OwnCloud-Notes#53]
@stefan-niedermann I just checked out the card layout prototype. On a smartphone at least the layout makes it very difficult to have an overview. The cards have variable height, it's very difficult to scan, and you always have to switch left-right. :/

**Comment by HeaDBanGer84** [comment]
As I sad, for the first approach I oriented on the [Google Keep](https://play.google.com/store/apps/details?id=com.google.android.keep) App. I found it the perfect Notes app as I used a google account back in the days. The Cards are not necessarily related to the [StaggeredGridLayoutManager](https://developer.android.com/reference/android/support/v7/widget/StaggeredGridLayoutManager.html) with 2 Columns. The cards are choosen because they are more flexible to layout. (Can display reminders on them, which makes no sense in a webapp, but are very useful in an mobile application)
The Number of Columns could be set individually in the SettingsActivity and the default could be 1. Sorry for trying 2 Changes in one.

**Comment by jancborchardt** [comment]
Yeah, I can see where it's coming from. :)

Google Keep however does this because they have color-coded notes and pictures as well as other visual content. We don't have this (and it would be quite a big task and spec work needed to implement all that), so it makes less sense and mainly causes confusion because you don't really have visual anchors.

**Comment by jancborchardt** [comment]
cc @owncloud/designers on this FYI

**Comment by stefan-niedermann** [comment]
I just decided to keep the list layout (at least for now). i mailed @HeaDBanGer84 the reasons. sorry. hope, you still want to contribute :)

**Comment by jancborchardt** [comment]
@HeaDBanGer84 yeah, this is definitely not meant to be dismissive! :) But maybe that layout is not right for this app in the current state. Your contributions are very welcome though!

**Comment by HeaDBanGer84** [comment]
@jancborchardt I don't give up so fast. I desperatly look for a good note-taking solution, with sync support (I hate creating notes with an on-screen-keyboard) and a features, wich helps me keeping my thoughts togethter.
And perhaps in the future there will be picture support (markdown supports it anyway, but  have to be implemented in the oc-app first, makes the sync a lot harder (Perhaps needs an API change too :-( ).
And if I go crazy I think also on location/time-based Reminders which creates Notification under the set circumstances.
