### ISSUE TITLE
Feature Request: encrypt and decrypt note

### ISSUE THREAD

**Issue by dasmaetthes** [stefan-niedermann/OwnCloud-Notes#83]
Would be nice to have the possibility to encrypt and decrypt a note like you can do in [QOwnNotes](http://www.qownnotes.org)

If it would be even possible to decrypt the note which are encrypt with QOwnNotes and vice versa.

**Comment by stefan-niedermann** [comment]
How is QOwnNotes handling this? Are the encrypted notes readable via the ownCloud Notes (Server-) App? Or are the notes only encrypted on the mobile device and synced to server in plain text?

**Comment by dasmaetthes** [comment]
QOwnNotes isn't a mobile app, it's a desktop application written in Qt. It uses the library [SimpleCrypt](https://wiki.qt.io/Simple_encryption_with_SimpleCrypt) for en-/decryption.

So a note looks like following in the usual txt file:
``

So it can be still synced with ownCloud notes as usual but to decrypt and read you need to use QOwnNotes

**Comment by stefan-niedermann** [comment]
Well - i'm just asking myself where the key is stored? If the key are stored **in** the encryption would not be very useful. If the key stays at the local machine where you run QOwnNotes no other app will be able to decrypt the notes because the key is missing.

**Comment by dasmaetthes** [comment]
Well, the key is stored on local machine, so would only work if there would be a way to sync also the key.
Just generally it would be also nice to have this future independent from QOwnNotes in your App

**Comment by stefan-niedermann** [comment]
So syncing generally works. You may want to open an issue in the [server app](https://github.com/owncloud/notes/issues) to provide an api which could be used from other clients? I currently am not able to implement something as long as there is no api for it, sorry.

**Comment by stefan-niedermann** [comment]
@dasmaetthes did you open an issue in the server app repository? I can't see what i can do on the android client if there is no server side API.

**Comment by pbek** [comment]
The key is generated from the password one uses on the note and has just 64 bit, which can't really be called "strong encryption", but enough to hide sensitive stuff from plain sight.
https://github.com/pbek/QOwnNotes/blob/develop/src/libraries/simplecrypt/simplecrypt.cpp

**Comment by X4fyr** [comment]
Why not using a binding to OpenKeyChain aka. gpg/pgp. This solves the problem of the key by shifting it to the OpenKeychain App.

**Comment by Henni** [comment]
I believe the way to go is to encrypt the note server-side and client-side independently and to sync in "plaintext" (over TLS).

cc @LukasReschke

**Comment by stefan-niedermann** [comment]
I spent a little time on thinking about this issue and i my conclusion is: i agree to @Henni.
1. on server the notes are stored as files which can be encrypted
2. on transport to or from the clients the notes are protected by TLS
3. on clients well, it could make sense to encrypt them locally

so suma sumarum:
**What is really needed?** Encrypt the local database and ask for password on every time opening the app
**When is this useful?** If you lose your device or if you have rooted device

Everything else does simply not make sense to me. You can open a new issue for local-app-protection if you want, but i will not have time to implement it *now* since there are more urgent issues and i have very little time to work on this project.

Sorry and thanks for feature request.

**Comment by pbek** [comment]
I agree to @stefan-niedermann.
Plus meanwhile QOwnNotes can encrypt selected notes with AES-256.
